package model.pojo;
// Generated Jun 4, 2017 3:51:55 PM by Hibernate Tools 4.3.1



/**
 * Livros generated by hbm2java
 */
public class Livros  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private String descricao;
     private String categoria;
     private String autor;
     private Float valor;
     private String link;

    public Livros() {
    }

    public Livros(String nome, String descricao, String categoria, String autor, Float valor, String link) {
       this.nome = nome;
       this.descricao = descricao;
       this.categoria = categoria;
       this.autor = autor;
       this.valor = valor;
       this.link = link;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
}


